#!/usr/bin/env python3
"""
Feedback Analysis Script

This script analyzes the feedback logs generated by the WebReranker extension
to understand user preferences and result quality patterns.
"""

import json
import os
from collections import defaultdict, Counter
from datetime import datetime
from typing import Dict, List, Any
import argparse

def load_feedback_logs(log_dir: str = "feedback_logs") -> List[Dict[str, Any]]:
    """Load all feedback entries from log files."""
    feedback_entries = []

    if not os.path.exists(log_dir):
        print(f"Log directory '{log_dir}' does not exist.")
        return feedback_entries

    for filename in os.listdir(log_dir):
        if filename.startswith("feedback_") and filename.endswith(".jsonl"):
            filepath = os.path.join(log_dir, filename)
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    for line in f:
                        if line.strip():
                            entry = json.loads(line)
                            feedback_entries.append(entry)
            except Exception as e:
                print(f"Error reading {filepath}: {e}")

    return feedback_entries

def analyze_feedback(feedback_entries: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Analyze feedback data and return statistics."""
    if not feedback_entries:
        return {"error": "No feedback data found"}

    stats = {
        "total_entries": len(feedback_entries),
        "date_range": {},
        "feedback_distribution": Counter(),
        "signal_type_distribution": Counter(),
        "top_domains_positive": Counter(),
        "top_domains_negative": Counter(),
        "search_engines": Counter(),
        "hourly_distribution": Counter(),
        "daily_distribution": Counter(),
        "explicit_vs_implicit": {"explicit": 0, "implicit": 0}
    }

    for entry in feedback_entries:
        # Basic counts
        feedback = entry.get("feedback", "unknown")
        signal_type = entry.get("signalType", "unknown")
        stats["feedback_distribution"][feedback] += 1
        stats["signal_type_distribution"][signal_type] += 1

        # Classify explicit vs implicit
        if signal_type in ['thumbs_up', 'thumbs_down']:
            stats["explicit_vs_implicit"]["explicit"] += 1
        else:
            stats["explicit_vs_implicit"]["implicit"] += 1

        # Domain analysis
        result_url = entry.get("result", {}).get("url", "")
        if result_url:
            try:
                from urllib.parse import urlparse
                domain = urlparse(result_url).netloc.lower()
                if domain.startswith('www.'):
                    domain = domain[4:]

                if feedback == "positive":
                    stats["top_domains_positive"][domain] += 1
                elif feedback == "negative":
                    stats["top_domains_negative"][domain] += 1
            except:
                pass

        # Search engine analysis
        page_url = entry.get("pageUrl", "")
        if page_url:
            try:
                from urllib.parse import urlparse
                domain = urlparse(page_url).netloc.lower()
                if "google" in domain:
                    stats["search_engines"]["Google"] += 1
                elif "bing" in domain:
                    stats["search_engines"]["Bing"] += 1
                elif "duckduckgo" in domain:
                    stats["search_engines"]["DuckDuckGo"] += 1
                else:
                    stats["search_engines"]["Other"] += 1
            except:
                pass

        # Time analysis
        timestamp = entry.get("timestamp", "")
        if timestamp:
            try:
                dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
                stats["hourly_distribution"][dt.hour] += 1
                stats["daily_distribution"][dt.date()] += 1

                if not stats["date_range"]:
                    stats["date_range"] = {"start": dt.date(), "end": dt.date()}
                else:
                    stats["date_range"]["start"] = min(stats["date_range"]["start"], dt.date())
                    stats["date_range"]["end"] = max(stats["date_range"]["end"], dt.date())
            except:
                pass

    return stats

def print_analysis(stats: Dict[str, Any]):
    """Print formatted analysis results."""
    print("=== WebReranker Feedback Analysis ===\n")

    if "error" in stats:
        print(stats["error"])
        return

    print(f"Total feedback entries: {stats['total_entries']}")
    print(f"Date range: {stats['date_range'].get('start', 'N/A')} to {stats['date_range'].get('end', 'N/A')}\n")

    print("Feedback Distribution:")
    total = sum(stats['feedback_distribution'].values())
    for feedback_type, count in stats['feedback_distribution'].most_common():
        percentage = (count / total * 100) if total > 0 else 0
        print(f"  {feedback_type}: {count} ({percentage:.1f}%)")
    print()

    print("Signal Type Distribution:")
    for signal_type, count in stats['signal_type_distribution'].most_common():
        percentage = (count / total * 100) if total > 0 else 0
        print(f"  {signal_type}: {count} ({percentage:.1f}%)")
    print()

    explicit_total = stats['explicit_vs_implicit']['explicit'] + stats['explicit_vs_implicit']['implicit']
    if explicit_total > 0:
        print("Explicit vs Implicit Feedback:")
        explicit_pct = (stats['explicit_vs_implicit']['explicit'] / explicit_total * 100)
        implicit_pct = (stats['explicit_vs_implicit']['implicit'] / explicit_total * 100)
        print(f"  Explicit (thumbs up/down): {stats['explicit_vs_implicit']['explicit']} ({explicit_pct:.1f}%)")
        print(f"  Implicit (clicks/skips): {stats['explicit_vs_implicit']['implicit']} ({implicit_pct:.1f}%)")
        print()

    print("Top 10 Positive Domains:")
    for domain, count in stats['top_domains_positive'].most_common(10):
        print(f"  {domain}: {count}")
    print()

    print("Top 10 Negative Domains:")
    for domain, count in stats['top_domains_negative'].most_common(10):
        print(f"  {domain}: {count}")
    print()

    print("Search Engine Usage:")
    for engine, count in stats['search_engines'].most_common():
        print(f"  {engine}: {count}")
    print()

    print("Hourly Activity (UTC):")
    for hour in range(24):
        count = stats['hourly_distribution'].get(hour, 0)
        print(f"  {hour:2d}:00 - {count} feedback entries")

def main():
    parser = argparse.ArgumentParser(description="Analyze WebReranker feedback logs")
    parser.add_argument("--log-dir", default="feedback_logs", help="Directory containing feedback logs")
    args = parser.parse_args()

    feedback_entries = load_feedback_logs(args.log_dir)
    stats = analyze_feedback(feedback_entries)
    print_analysis(stats)

if __name__ == "__main__":
    main()